#!/usr/bin/env bash

#Start-server at boot
sudo cp start-server.service /etc/systemd/system/
sudo systemctl enable start-server.service

#Install RPI Cam From https://github.com/silvanmelchior/RPi_Cam_Web_Interface
git clone https://github.com/silvanmelchior/RPi_Cam_Web_Interface.git
cd RPi_Cam_Web_Interface
chmod u+x *.sh
./install.sh

#Install Python Libraries
sudo apt-get install python-pip
sudo pip install requests

echo 'Go here to enable less secure apps:'
echo 'https://www.google.com/settings/security/lesssecureapps'
