#!/usr/bin/env bash


#Install RPI Cam From https://github.com/silvanmelchior/RPi_Cam_Web_Interface
git clone https://github.com/silvanmelchior/RPi_Cam_Web_Interface.git
cd RPi_Cam_Web_Interface
chmod u+x *.sh
./install.sh

#Install Python Libraries
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
rm get-pip.py
sudo pip install requests

#Start-server at boot
cd ..
sudo python rclocal.py

echo 'Go here to enable less secure apps:'
echo 'https://www.google.com/settings/security/lesssecureapps'
