#!/usr/bin/env bash


#Install RPI Cam From https://github.com/silvanmelchior/RPi_Cam_Web_Interface
git clone https://github.com/silvanmelchior/RPi_Cam_Web_Interface.git
cd RPi_Cam_Web_Interface
chmod u+x *.sh
./install.sh

#Install Python Libraries
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
rm get-pip.py
sudo pip install requests

#Start-server at boot
cd ..
sudo crontab -l > mycron
echo "@reboot $PWD/start-server.py" >> mycron
crontab mycron
rm mycron

